package eu.jgdi.mc.map2mc.model.minecraft;

import java.util.Map;

import static java.util.Map.entry;

public enum Block {

    DIRT("dirt"),
    STONE("stone"),
    UNKNOWN("gold_block"),
    WATER("water"),
    BEDROCK("bedrock"),
    COAL_ORE("coal_ore"),
    IRON_ORE("iron_ore"),
    GOLD_ORE("gold_ore"),
    DIAMOND_ORE("diamond_ore"),
    EMERALD_ORE("emerald_ore");

    public static String UNDEFINED = "--undefined--";

    public static String AIR = "air";

    private final String blockId;

    Block(String id) {
        this.blockId = id;
    }

    public String getBlockId() {
        return blockId;
    }

    public static final Map<String, BlockTick> BLOCK_INFO = Map.ofEntries(
            entry(UNDEFINED, BlockTick.STATIC), // do not warn, wenn some mappings are undefined
            entry(AIR, BlockTick.STATIC), // do not warn, wenn some mappings are undefined
            // Blocks:
            entry("acacia_sapling", BlockTick.STATIC),
            entry("allium", BlockTick.STATIC),
            entry("andesite", BlockTick.STATIC),
            entry("azure_bluet", BlockTick.STATIC),
            entry("bamboo", BlockTick.STATIC),
            entry("bee_hive", BlockTick.STATIC),
            entry("bee_nest", BlockTick.STATIC),
            entry("beetroots", BlockTick.STATIC),
            entry("birch_fence", BlockTick.STATIC),
            entry("birch_leaves", BlockTick.STATIC),
            entry("birch_log", BlockTick.STATIC),
            entry("birch_planks", BlockTick.STATIC),
            entry("birch_sapling", BlockTick.TICK),
            entry("birch_slab", BlockTick.STATIC),
            entry("black_concrete", BlockTick.STATIC),
            entry("black_concrete_powder", BlockTick.STATIC),
            entry("blue_orchid", BlockTick.STATIC),
            entry("brain_coral", BlockTick.STATIC),
            entry("brain_coral_block", BlockTick.STATIC),
            entry("brain_coral_fan", BlockTick.STATIC),
            entry("bricks", BlockTick.STATIC),
            entry("brown_mushroom", BlockTick.STATIC),
            entry("bubble_coral", BlockTick.STATIC),
            entry("bubble_coral_block", BlockTick.STATIC),
            entry("bubble_coral_fan", BlockTick.STATIC),
            entry("bubble_column", BlockTick.STATIC),
            entry("cactus", BlockTick.STATIC),
            entry("campfire", BlockTick.STATIC),
            entry("carrots", BlockTick.STATIC),
            entry("clay_block", BlockTick.STATIC),
            entry("coarse_dirt", BlockTick.STATIC),
            entry("cobblestone", BlockTick.STATIC),
            entry("cobweb", BlockTick.STATIC),
            entry("cornflower", BlockTick.STATIC),
            entry("cracked_stone_bricks", BlockTick.STATIC),
            entry("cut_red_sandstone", BlockTick.STATIC),
            entry("cut_sandstone", BlockTick.STATIC),
            entry("cyan_concrete", BlockTick.STATIC),
            entry("cyan_concrete_powder", BlockTick.STATIC),
            entry("dandelion", BlockTick.STATIC),
            entry("dark_oak_fence", BlockTick.STATIC),
            entry("dark_oak_leaves", BlockTick.STATIC),
            entry("dark_oak_log", BlockTick.STATIC),
            entry("dark_oak_planks", BlockTick.STATIC),
            entry("dark_oak_sapling", BlockTick.TICK),
            entry("dark_oak_slab", BlockTick.STATIC),
            entry("dead_bush", BlockTick.STATIC),
            entry("diorite", BlockTick.STATIC),
            entry("dirt", BlockTick.STATIC),
            entry("farmland", BlockTick.STATIC),
            entry("fern", BlockTick.STATIC),
            entry("fire_coral", BlockTick.STATIC),
            entry("fire_coral_block", BlockTick.STATIC),
            entry("fire_coral_fan", BlockTick.STATIC),
            entry("gold_block", BlockTick.STATIC),
            entry("granite", BlockTick.STATIC),
            entry("grass", BlockTick.STATIC),
            entry("grass_block", BlockTick.STATIC),
            entry("grass_path", BlockTick.STATIC),
            entry("gravel", BlockTick.STATIC),
            entry("gray_concrete", BlockTick.STATIC),
            entry("gray_concrete_powder", BlockTick.STATIC),
            entry("green_concrete", BlockTick.STATIC),
            entry("green_concrete_powder", BlockTick.STATIC),
            entry("hay_block", BlockTick.STATIC),
            entry("horn_coral", BlockTick.STATIC),
            entry("horn_coral_block", BlockTick.STATIC),
            entry("horn_coral_fan", BlockTick.STATIC),
            entry("ice", BlockTick.STATIC),
            entry("iron_bars", BlockTick.STATIC),
            entry("jungle_leaves", BlockTick.STATIC),
            entry("jack_o_lantern", BlockTick.STATIC),
            entry("jungle_log", BlockTick.STATIC),
            entry("jungle_sapling", BlockTick.TICK),
            entry("kelp", BlockTick.STATIC),
            entry("kelp_plant", BlockTick.STATIC),
            entry("lantern", BlockTick.STATIC),
            entry("large_fern", BlockTick.STATIC),
            entry("lava", BlockTick.STATIC),
            entry("light_blue_concrete", BlockTick.STATIC),
            entry("light_blue_concrete_powder", BlockTick.STATIC),
            entry("lilac", BlockTick.STATIC),
            entry("lily_of_the_valley", BlockTick.STATIC),
            entry("magenta_concrete", BlockTick.STATIC),
            entry("magenta_concrete_powder", BlockTick.STATIC),
            entry("melon", BlockTick.STATIC),
            entry("melon_stem", BlockTick.STATIC),
            entry("mossy_stone_bricks", BlockTick.STATIC),
            entry("mossy_stone_brick_slab", BlockTick.STATIC),
            entry("mossy_stone_brick_wall", BlockTick.STATIC),
            entry("mycelium", BlockTick.STATIC),
            entry("oak_fence", BlockTick.STATIC),
            entry("oak_leaves", BlockTick.STATIC),
            entry("oak_log", BlockTick.STATIC),
            entry("oak_planks", BlockTick.STATIC),
            entry("oak_sapling", BlockTick.TICK),
            entry("oak_slab", BlockTick.STATIC),
            entry("obsidian", BlockTick.STATIC),
            entry("orange_tulip", BlockTick.STATIC),
            entry("oxeye_daisy", BlockTick.STATIC),
            entry("packed_ice", BlockTick.STATIC),
            entry("peony", BlockTick.STATIC),
            entry("pink_tulip", BlockTick.STATIC),
            entry("podzol", BlockTick.STATIC),
            entry("polished_andesite", BlockTick.STATIC),
            entry("polished_diorite", BlockTick.STATIC),
            entry("poppy", BlockTick.STATIC),
            entry("potatoes", BlockTick.STATIC),
            entry("pumpkin", BlockTick.STATIC),
            entry("pumpkin_stem", BlockTick.STATIC),
            entry("quartz_block", BlockTick.STATIC),
            entry("quartz_pillar", BlockTick.STATIC),
            entry("red_concrete", BlockTick.STATIC),
            entry("red_concrete_powder", BlockTick.STATIC),
            entry("red_mushroom", BlockTick.STATIC),
            entry("red_sand", BlockTick.STATIC),
            entry("red_sandstone", BlockTick.STATIC),
            entry("red_tulip", BlockTick.STATIC),
            entry("redstone_torch", BlockTick.STATIC),
            entry("rose_bush", BlockTick.STATIC),
            entry("sand", BlockTick.STATIC),
            entry("sandstone", BlockTick.STATIC),
            entry("sea_lantern", BlockTick.STATIC),
            entry("sea_pickle", BlockTick.STATIC),
            entry("seagrass", BlockTick.STATIC),
            entry("soul_sand", BlockTick.STATIC),
            entry("smooth_quartz", BlockTick.STATIC),
            entry("smooth_red_sandstone", BlockTick.STATIC),
            entry("smooth_sandstone", BlockTick.STATIC),
            entry("snow_block", BlockTick.STATIC),
            entry("spruce_log", BlockTick.STATIC),
            entry("spruce_slab", BlockTick.STATIC),
            entry("spruce_sapling", BlockTick.TICK),
            entry("stick", BlockTick.STATIC),
            entry("stone", BlockTick.STATIC),
            entry("stone_brick_slab", BlockTick.STATIC),
            entry("stone_bricks", BlockTick.STATIC),
            entry("sugar_cane", BlockTick.STATIC),
            entry("sweet_berries", BlockTick.STATIC),
            entry("tall_grass", BlockTick.STATIC),
            entry("torch", BlockTick.STATIC),
            entry("tube_coral_block", BlockTick.STATIC),
            entry("tube_coral_fan", BlockTick.STATIC),
            entry("water", BlockTick.STATIC),
            entry("wheat", BlockTick.STATIC),
            entry("white_concrete", BlockTick.STATIC),
            entry("white_concrete_powder", BlockTick.STATIC),
            entry("white_tulip", BlockTick.STATIC),
            entry("wither_rose", BlockTick.STATIC),
            entry("yellow_concrete", BlockTick.STATIC),
            entry("anvil", BlockTick.STATIC),
            entry("barrel", BlockTick.STATIC),
            entry("cake", BlockTick.STATIC),
            entry("enchanting_table", BlockTick.STATIC),
            entry("ender_chest", BlockTick.STATIC),
            entry("glowstone", BlockTick.STATIC),
            entry("potted_bamboo", BlockTick.STATIC),
            entry("spruce_boat", BlockTick.STATIC),
            entry("yellow_concrete_powder", BlockTick.STATIC)
    );
}
